name: tugasrestapi
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  vania: ^0.6.2


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.6

dependency_overrides:
  pointycastle: 3.7.3